[package]
name = "lhi"
version = "0.0.2"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/lhi"
description = "Lightweight HTTP library"
readme = "README.md"

[dependencies]
kern = "1.1.6"
rustls = "0.19.0"
