[package]
name = "lhi"
version = "0.0.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/lhi"
description = "Lightweight HTTP library"
readme = "README.md"

[dependencies]
rustls = "0.17.0"
